group 'com.jhomlala.better_player.better_player'
version '1.0-SNAPSHOT'

buildscript {
    ext.mediaVersion = "1.8.0"
    ext.lifecycleVersion = "2.9.3"
    ext.annotationVersion = "1.9.1"
    ext.workVersion = "2.10.4"
    ext.coreVersion = "1.13.1"
    ext.gradleVersion = "8.5.0"
    ext.kotlinVersion = "2.2.20"

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$gradleVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 36
    namespace 'com.jhomlala.better_player.better_player'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }

    dependencies {
        implementation "androidx.media3:media3-exoplayer:$mediaVersion"
        implementation "androidx.media3:media3-exoplayer-hls:$mediaVersion"
        implementation "androidx.media3:media3-exoplayer-dash:$mediaVersion"
        implementation "androidx.media3:media3-exoplayer-smoothstreaming:$mediaVersion"
        implementation "androidx.media3:media3-ui:$mediaVersion"
        implementation "androidx.media3:media3-session:$mediaVersion"
        implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"
        implementation "androidx.annotation:annotation:$annotationVersion"
        implementation "androidx.work:work-runtime:$workVersion"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
}
